baseurl = "https://pt.trunkbaseddevelopment.com/"
languageCode = "en-us"
title = "Desenvolvimento Baseado em Trunk"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-24415524-3"

[params]
	# General information
	author = "paul-hammant"
	description = "A portal on this practice"
	copyright = "TrunkBasedDevelopment.com's contributors."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/paul-hammant/tbd"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "paul-hammant"
	email   = "paul@hammant.org"

[[menu.main]]
	name   = "Introdução"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Contexto"
	url    = "context/"
	weight = 5

[[menu.main]]
	name   = "Visão geral em 5 minutos"
	url    = "5-min-overview/"
	weight = 11

[[menu.main]]
	name   = "Fatores decisivos"
	url    = "deciding-factors/"
	weight = 21

[[menu.main]]
	name   = "Características de Sistemas de Controle de Versões"
	url    = "vcs-features/"
	weight = 31

[[menu.main]]
	name   = "Escolhas de Sistemas de Controle de Versão"
	url    = "vcs-choices/"
	weight = 32

[[menu.main]]
	name   = "Feature flags"
	url    = "feature-flags/"
	weight = 41

[[menu.main]]
	name   = "Branch por Abastração"
	url    = "branch-by-abstraction/"
	weight = 53

[[menu.main]]
	name   = "Release Branch"
	url    = "branch-for-release/"
	weight = 55

[[menu.main]]
	name   = "Release gerada a partir do trunk"
	url    = "release-from-trunk/"
	weight = 56

[[menu.main]]
	name   = "Integração Contínua (IC)"
	url    = "continuous-integration/"
	weight = 61

[[menu.main]]
	name   = "Commit direto para Trunk"
	url    = "committing-straight-to-the-trunk/"
	weight = 62

[[menu.main]]
	name   = "Feature Branches de vida curta"
	url    = "short-lived-feature-branches/"
	weight = 63

[[menu.main]]
	name   = "Revisão Contínua"
	url    = "continuous-review/"
	weight = 65

[[menu.main]]
	name   = "Entrega Contínua (EC)"
	url    = "continuous-delivery/"
	weight = 71

[[menu.main]]
	name   = "Desenvolvimento concorrente de releases consecutivas"
	url    = "concurrent-development-of-consecutive-releases/"
	weight = 75

[[menu.main]]
	name   = "Estrangulação de aplicação"
	url    = "strangulation/"
	weight = 78

[[menu.main]]
	name   = "Hábitos"
	url    = "observed-habits/"
	weight = 81

[[menu.main]]
	name   = "Você está fazendo isso errado"
	url    = "youre-doing-it-wrong/"
	weight = 91

[[menu.main]]
	name   = "Modelos alternativos"
	url    = "alternative-branching-models/"
	weight = 101

[[menu.main]]
	name   = "Monorepos"
	url    = "monorepos/"
	weight = 111

[[menu.main]]
	name   = "Expandindo e Contraindo Monorepos"
	url    = "expanding-contracting-monorepos/"
	weight = 112

[[menu.main]]
	name   = "Game Changers"
	url    = "game-changers/"
	weight = 121

[[menu.main]]
	name   = "Publicações"
	url    = "publications/"
	weight = 131

[[menu.main]]
	name   = "Livro"
	url    = "book/"
	weight = 132

[[menu.main]]
	name   = "Diagrama"
	url    = "key/"
	weight = 141

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
